# Generated by Django 2.1.3 on 2018-11-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='workout_name',
        ),
        migrations.AddField(
            model_name='post',
            name='rep_amount',
            field=models.CharField(default='5', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='set_amount',
            field=models.CharField(default='5', max_length=100),
        ),
    ]
