# Generated by Django 2.1.3 on 2018-11-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181121_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rep_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='set_amount',
            field=models.IntegerField(),
        ),
    ]
